# Generated by Django 6.1.1 on 2026-09-08 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, help_text='Unique tracking identifier e.g., TRK-984210', max_length=50, unique=True)),
                ('destination', models.TextField(help_text='Full delivery address')),
                ('driver_name', models.CharField(blank=True, default='', help_text='Name of assigned driver or empty string if unassigned', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
