# Generated by Django 6.1.1 on 2026-09-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique tracking identifier (e.g., TRK-984210)', max_length=50, unique=True),
        ),
    ]
