# Generated by Django 6.1.1 on 2026-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='destination',
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_address',
            field=models.CharField(default='', help_text='Formatted address string from map selection', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (e.g. 40.712800)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (e.g. -74.006000)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
