# Generated by Django 6.1.1 on 2026-09-15 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_shipment_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Driver's full name", max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Primary contact phone number', max_length=20)),
                ('license_number', models.CharField(blank=True, help_text="Driver's commercial license identifier", max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('OFF_DUTY', 'Off Duty')], db_index=True, default='AVAILABLE', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Assigned driver, or null if unassigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipments.driver'),
        ),
    ]
